[2023-06-03T18:25:46.611+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: apresentacao_airflow.extracao_dados_pockemon scheduled__2023-06-03T16:30:00+00:00 [queued]>
[2023-06-03T18:25:46.617+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: apresentacao_airflow.extracao_dados_pockemon scheduled__2023-06-03T16:30:00+00:00 [queued]>
[2023-06-03T18:25:46.617+0000] {taskinstance.py:1308} INFO - Starting attempt 10 of 10
[2023-06-03T18:25:46.629+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extracao_dados_pockemon> on 2023-06-03 16:30:00+00:00
[2023-06-03T18:25:46.632+0000] {standard_task_runner.py:57} INFO - Started process 1188 to run task
[2023-06-03T18:25:46.634+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'apresentacao_***', 'extracao_dados_pockemon', 'scheduled__2023-06-03T16:30:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/***-example.py', '--cfg-path', '/tmp/tmpf_79g9l3']
[2023-06-03T18:25:46.635+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask extracao_dados_pockemon
[2023-06-03T18:25:46.663+0000] {task_command.py:410} INFO - Running <TaskInstance: apresentacao_airflow.extracao_dados_pockemon scheduled__2023-06-03T16:30:00+00:00 [running]> on host 7e08fa621370
[2023-06-03T18:25:46.710+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='apresentacao_***' AIRFLOW_CTX_TASK_ID='extracao_dados_pockemon' AIRFLOW_CTX_EXECUTION_DATE='2023-06-03T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-03T16:30:00+00:00'
[2023-06-03T18:25:46.714+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-example.py", line 13, in extracao_dados_pockemon
    df = pd.read_csv('./pokemon.csv', delimiter=',', skiprows=1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './pokemon.csv'
[2023-06-03T18:25:46.720+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=apresentacao_***, task_id=extracao_dados_pockemon, execution_date=20230603T163000, start_date=20230603T182546, end_date=20230603T182546
[2023-06-03T18:25:46.727+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task extracao_dados_pockemon ([Errno 2] No such file or directory: './pokemon.csv'; 1188)
[2023-06-03T18:25:46.766+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-03T18:25:46.797+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
